### ISSUE TITLE
whatcha doin lately

### ISSUE THREAD

**Issue by gek169** [alloca123/based-ssg#2]
just wondering

**Comment by alloca123** [comment]
somewhat busy doing stuff irl. Have also been working on my site alloca.dev, and been learning golang so i can do cooler shit with alloca.dev. I've written a basic pastebin and stuff in golang, but looking to do cooler things

**Comment by gek169** [comment]
neato

**Comment by gek169** [comment]
do you want to try my virtual machine

**Comment by alloca123** [comment]
sure

**Comment by gek169** [comment]
https://github.com/gek169/Simple_ISA
