### ISSUE TITLE
Memory corruption all over the place

### ISSUE THREAD

**Issue by SpectreVert** [alloca123/based-ssg#3]
I think this could be a very nice program. But have you ever run it using valgrind? You have a little under 100 places with memory corruption; double frees, access after free and all sorts of weird stuff. I would seriously consider using this as my go to site generator but man I really can't given how unstable the program looks.

**Comment by alloca123** [comment]
i did run valgrind and got no realerrors. the only error i got was "Use of uninitialised value of size 8", which even the command cat gets. There is not double frees, access after free, or any of that stuff as far as i'm aware.

**Comment by alloca123** [comment]
yeah i really can't find many real memory corruption errors. based-ssg may have spaghetti code, but it does not have memory corruption all over the place

**Comment by alloca123** [comment]
the whole "Use of uninitialised value of size 8" really isn't a big deal, a bunch of software including cat gets the same thing.
