### ISSUE TITLE
doesn't support <> tags on markdown

### ISSUE THREAD

**Issue by suborbitalrat** [alloca123/based-ssg#5]
doesn't support <> tags on markdown
see images
1: text in markdown file
2: text in html file
![image](https://user-images.githubusercontent.com/111161640/184750720-5df0ed16-c731-42de-8686-d6d52366051f.png)
![image](https://user-images.githubusercontent.com/111161640/184751350-8b2fac9d-3ca5-4923-b291-7ed74e7e660a.png)

**Comment by nicoleaoki** [comment]
Doubling down on this, I recently contacted the developer and got this as a reply

![image](https://user-images.githubusercontent.com/105708902/184752310-2d23a56d-7c90-4006-9284-580797e64ca3.png)

It seems that @alloca123 is just an irresponsible developer who will develop a SSG without even following the [base specifications](https://daringfireball.net/projects/markdown/).

**Comment by nicoleaoki** [comment]
For now, our really important and big-money enterprise will nolonger use based-ssg for our projects, we recommend the developer of this software to reconsider their life choices and to reimplement their software supporting standardized Markdown and [CommonMark 0.30](https://spec.commonmark.org/0.30/).

With that in mind, thank you and I hope you explode.

**Comment by suborbitalrat** [comment]
** With that in mind, thank you and I hope you explode.

**Comment by alloca123** [comment]
Too much effort to rewrite libsmu, little value in that feature, base specifications are bloat and can suck my dick, also you can just write an m4 macro or something if you really care that much

**Comment by suborbitalrat** [comment]
We do not care. Fix it if you want people to use this.
On a personal note I might just fork it and fix JUST this and make a PR just to fill your email with more spam.

**Comment by alloca123** [comment]
alright if you fork it and fix it(without breaking other features) that's great.

**Comment by suborbitalrat** [comment]
piss
